export const studies = [
  {
    title: "Higher Degree in Multiplatform Application Development",
    corporation: "iFP, Seville",
    date: "Sep 2022 - Jun 2024",
  },
  {
    title: "Degree in Advertising and Public Relations",
    corporation: "EUSA University, Seville",
    date: "Sep 2018 - Sep 2022",
  },
  {
    title: "High School",
    corporation: "El Centro Inglés, El Puerto de Santa María, Cádiz",
    date: "Sep 2010 - Jun 2017",
  },
];

export const IconKeys = {
  angular: "angular",
  ionic: "ionic",
  html: "html",
  css: "css",
  java: "java",
  javaScript: "javaScript",
  react: "react",
  astro: "astro",
  materialUi: "materialUi",
  nextjs: "nextjs",
  redux: "redux",
  styled: "styled",
  tailwind: "tailwind",
  radix: "radix",
  reactQuery: "reactQuery",
  typeScript: "typeScript",
  zustand: "zustand",
  git: "git",
  github: "github",
  stripe: "stripe",
  shadcn: "shadcn",
  nodejs: "nodejs",
  mongodb: "mongodb",
  vite: "vite",
  visualStudio: "visualStudio",
  android: "android"
};

export const skills = [
  { title: "Angular", icon: IconKeys.angular },
  { title: "Ionic", icon: IconKeys.ionic },
  { title: "HTML", icon: IconKeys.html },
  { title: "CSS", icon: IconKeys.css },
  { title: "Java", icon: IconKeys.java },
  { title: "Astro", icon: IconKeys.astro },
  { title: "React Js", icon: IconKeys.react },
  { title: "Git", icon: IconKeys.git },
  { title: "Github", icon: IconKeys.github },
  { title: "Node Js", icon: IconKeys.nodejs },
  { title: "TypeScript", icon: IconKeys.typeScript },
  { title: "Visual Studio", icon: IconKeys.visualStudio },
  { title: "Android Studio", icon: IconKeys.android },
];

export const projects = [
  {
    img: "../../../img/little_thai.webp",
    title: "Little Thai",
    link: "https://github.com/carlosgjim98/app-little-thai",
    video:"/vids/little-thai.mp4",
    description: `App for orders, reservations, and promotions of Little Thai restaurants. "In Development"`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
  {
    img: "../../../img/guamigo2.webp",
    title: "Guaumigo",
    link: "https://github.com/carlosgjim98/app-guaumigos",
    video: "/vids/app-perros.mp4",
    description: `App that connects dog owners with trusted dog walkers across Spain without charging a commission.`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
  {
    img: "../../../img/valorant.webp",
    title: "Valorant Stats",
    link: "https://github.com/carlosgjim98/Valo-app",
    video: "",
    description: `App that tracks competitive Valorant stats in real-time (still in development).`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
  {
    img: "../../../img/jdv-1.webp",
    title: "JDV",
    link: "https://github.com/carlosgjim98/app-inversiones",
    video: "/vids/JDV-app.mp4",
    description: `Intuitive app to invest, manage your portfolio, and follow the market in real-time.`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
  {
    img: "../../../img/citas.webp",
    title: "Dating App",
    link: "https://github.com/carlosgjim98/app-citas",
    video: "/vids/app-citas.mp4",
    description: `Dating app to connect like-minded people, facilitate meetings, and create real connections...`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
  {
    img: "../../../img/app-musica.webp",
    title: "WoWeLike",
    link: "https://github.com/carlosgjim98/app-clickcomun",
    description: `Music app to create and share playlists, chat with friends, and discover new sounds together.`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
  {
    img: "../../../img/policia.webp",
    title: "Police Reports App",
    link: "https://github.com/carlosgjim98/app-policia",
    video: "/vids/policia-local-alcudia.mp4",
    description: `App by the Alcúdia Local Police to file reports, report incidents, and access security services quickly and efficiently.`,
    technologies: [
      { icon: IconKeys.typeScript },
      { icon: IconKeys.html },
      { icon: IconKeys.css },
      { icon: IconKeys.ionic },
      { icon: IconKeys.angular },
    ],
  },
];
